### PR TITLE
updated fr lang file

### PR DESCRIPTION
**Pull request by rockaddicted**

### CODE REVIEW

**Comment by nadenislamarre** [comment]
Hi,
you should remove the #fuzzy line above if you're sure about the translation.
I'll explain all that in a wiki when i'll finish with the correct translation of es.

**Comment by rockaddicted** [comment]
Yep I understood by testing my commits of yesterday.
I'll remove `#fuzzy` from others .po files.
So when there is a similar entry in the .po file, an automatic translation is added, preceded by `#fuzzy` ?

**Comment by nadenislamarre** [comment]
yes an no.
In my final version, i will remove the default fuzzy option that i don't
like.
it's sometimes usefull, but sometimes not good at all.

Good case :
if you change : "the game is startin" by "the game is starting"

in the french po, it will replace :
"the game is startin"
"le jeu démarre"

par

# fuzzy

"the game is starting"
"le jeu démarre"

but sometimes, it does it for things having not the same meaning when you
add a new translation like :
"the car is starting"
is automatically translated by :

# fuzzy

"Le jeu démarre"

so, i find it not nice. I prefer that it is displayed in english and that
the translator check things.

2016-02-09 9:00 GMT+01:00 rockaddicted notifications@github.com:

**Comment by rockaddicted** [comment]
:+1: 
Indeed, yesterday, I had this problem with my translations.
"RETROACHIEVEMENTS SETTING" -> "OPTIONS DE JEUX"
etc ... 

Thanks for the explanation :wink:

**Pull request merged**
