### PR TITLE
Updated spanish translation

### PR DESCRIPTION
**Pull request by emerrepengo**
Binari MO deleted
"Favorites" strings added to translation

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
The merge is failing. As we are bocking the translation file for the 3.3.0 beta, is it possible for you to update the translation and make a new pull request ?

Thanks pal.

**Comment by emerrepengo** [comment]
I'm not near my computer until next week. I will update on monday or tuesday and send the new pull.

**Comment by emerrepengo** [comment]
I updated the translation file. Now it should merge.

**Comment by digitalLumberjack** [comment]
Thank you

**Pull request merged**
