### PR TITLE
Update Turkish translation

### PR DESCRIPTION
**Pull request by igungor**

### CODE REVIEW

**Comment by nadenislamarre** [comment]
Hi,
thanks a lot.
What a reactivity !
I see some minor things to update if you think it could be usefull :

1) One string is missing.

msgid "GAME %i OF %i"
msgstr ""

2) The following translation seems strange while the singular form has no
word :

msgid "%i SELECTED"
msgid_plural "%i SELECTED"
msgstr[0] "%i"
msgstr[1] "%i SEÇİLİ"

3) i see no difference between the single and plural forms. Perhaps it's
normal. But i see that your language has 2 plural forms like in english.

4) Don't hesitate to remove the  #~ lines at the end of the file too.

NIcolas

**Comment by igungor** [comment]
Hey,
Thank you as well for overhauling the localisation plumbing :)

1) I know it is missing but Turkish locale is very different than English in terms of describing a ratio or a portion of a piece. There is no correct translation of this string (for myself), and honestly I prefer not to use patterns like "foo % of %" for cross-locale purposes. TL;DR, I purposely left it out since I don't have a _correct_ translation for it.

2) It seems wrong, let me update the PR. Thanks for the catch.

3) Yeah, there is no plural forms of such sentences in Turkish. This is the correct translation.

**Comment by digitalLumberjack** [comment]
Nice thank you @igungor

**Comment by nadenislamarre** [comment]
Ok, thanks.
I don't know the limitation to translate "%i of %i"

If needed, you can use the following syntaxe which allow to reverse the
number order :


"Only %2$i bytes free on '%1$i'."

which is semantically equivalent to

"'%i' has only %i bytes free."

2016-02-14 0:12 GMT+01:00 H. İbrahim Güngör notifications@github.com:

**Comment by nadenislamarre** [comment]
Or perhaps just translated by :
"%i/%i" to remove the english words.
As you think it is the best.

**Comment by igungor** [comment]
Thanks for the suggestions. I've translated such strings before but all of the translations were "weird". There are 3 incorrect ways to translate this string to Turkish and I think I'm going to use the least weird one: `game %i/%i`

Edit: See #89

**Pull request merged**
