### PR TITLE
Use Ubuntu Condensed font everywhere

### PR DESCRIPTION
**Pull request by igungor**
Even though the previous font (Opensans Hebrew Condensed) was easy on
the eyes, it lacks most if the latin-ext glyphs, resulting some of the
locales simply unreadable.

I've tried EncodeSans, which looks like Ubuntu and has much more styles
(thin, condensed, compressed, narrow etc.), it is still wider than
Ubuntu and makes the words collapse each other for small screen estates.

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
We'll test that

**Comment by igungor** [comment]
Sure, let me know if I can help.

**Comment by digitalLumberjack** [comment]
Works very good pal. Good choice for the font, it also have simplified chinese

**Comment by digitalLumberjack** [comment]
Next beta with 3 new languages supported !

**Comment by igungor** [comment]
Awesome, glad to hear that!

**Pull request merged**
