### PR TITLE
Improve Catalan translation

### PR DESCRIPTION
**Pull request by pereorga**
- Fixed a few typos, improved translations, fixed single quotes

- Translated new strings

My PO editor changed the format of a few lines automatically.

### CODE REVIEW

**Comment by paradadf** [comment]
I believe you must use the web interface for that...
https://forum.recalbox.com/topic/3845/recalbox-translations-you-can-help

EDIT: Apparently you can also translate directly to github XD

**Comment by digitalLumberjack** [comment]
The best is to use poeditor. The merges are really hard if we edit both sides ...

**Comment by digitalLumberjack** [comment]
so @pereorga if you can make the modifications on poeditor, that can be great. If not, let me know.

**Comment by pereorga** [comment]
I will, thanks

**Comment by pereorga** [comment]
Done.

**Pull request closed without merging**
