### PR TITLE
stdout: redirect launch stderr/stdout to files

### PR DESCRIPTION
**Pull request by nadenislamarre**
I don't know if path should be hardcoded or not here.

Signed-off-by: Nicolas Adenis-Lamarre <nicolas.adenis.lamarre@gmail.com>

### CODE REVIEW

**Comment by nadenislamarre** [comment]
i've added a security to limit the output to 300 lines.

**Comment by substring** [comment]
Very useful. Because of some very verbose emulators, would it be a bad idea to output to /tmp as @nadenislamarre thought in first intention, then append to a log file or gzip and copy to the logs folder ?

The reason is that if the bug occurs after the 300 lines of log, we missed it :/

**Comment by nadenislamarre** [comment]
keep it simple for the moment. we'll update later is necessary.
the aim is mainly in case of launch crash, so, only a view lines are
necessary

**Comment by digitalLumberjack** [comment]
great

**Pull request merged**
