### PR TITLE
Only save changed metadata while saving gamelist.xml

### PR DESCRIPTION
**Pull request by rtissera**
Please make sure your PR is ready to be merged !

- [X] You added the changes in CHANGELOG.md
- [X] You choose the right repository branch to make the PR
- [X] You described the PR as below

Fixes shutdown taking ages on systems with thousand of ROMs.

Changes :
- Only save changed metadata while saving gamelist.xml

Related to (put here the others PR in other repositories)
https://github.com/RetroPie/EmulationStation/commit/44ea23ae6ae8ace74193ebdc0a6e70f7f43b8e10

### CODE REVIEW

**Review by digitalLumberjack — APPROVED** [review]
Hi thanks for your contribution. I will test that and we will merge soon. Great job :)

**Comment by rockaddicted** [comment]
@rtissera Hi I'll test that this week.
Thank you for your pull request.

**Comment by rtissera** [comment]
Ok feel free to report any issue.
Please test with the two additional commits, it fixed a couple of problems on my side.

**Comment by rockaddicted** [comment]
@rtissera @digitalLumberjack 
So, I practiced some tests.
In a first time, I hadn't really a boost during the shutdown, because my `gamelist.xml` files only had informations about scraped games. And I have some systems with massive romsets, but with a very low % of scraped games.
So during the shutdown I had this seems of log : 
`Added/Updated 2217 entities in '/media/rockaddicted/stockage_250/recalbox/share/roms/apple2/gamelist.xml'`

So, in a second time, I rescraped all my romsets, using sselph's scraper and adding this option `-add_not_found=true` to have `gamelist.xml` files that reflects my FS.
And... miracle ... 1min14sec without this modification and 4sec with it. (tested on my PC, not rpi)

**Comment by rtissera** [comment]
I can confirm all tests on XU4, going from  > 30 minutes (bloated with many No Intro fullsets) to ~ 30 seconds.

**Comment by substring** [comment]
The fact is that not all users hit 100% games in gamelists. How can we still enjoy a fast shutdown when not all games are scrapped ?

**Comment by rtissera** [comment]
Only 80% of my games are scrapped and still it's a great improvement.

**Comment by paradadf** [comment]
hi @rtissera! did you also take a look at https://github.com/RetroPie/EmulationStation/pull/65?
this PR was merged before the one from verybadsoldier and maybe is the way to address the not scraped games?

**Comment by rtissera** [comment]
(edited again)
Let's merge this PR first and I will sort out https://github.com/RetroPie/EmulationStation/pull/65 changes in a separate one.

**Comment by rtissera** [comment]
Also please make sure to approve these two additional commits (after @digitalLumberjack approved original PR) for proper functionality :
https://github.com/recalbox/recalbox-emulationstation/pull/182/commits/c6b92eea26fb35d5de70b13783450d6bb506e4f3
https://github.com/recalbox/recalbox-emulationstation/pull/182/commits/fc93f1567cc745887fc576a64723904ce1fc708c

**Review by digitalLumberjack — APPROVED** [review]

**Comment by digitalLumberjack** [comment]
Great let's merge :)

**Comment by digitalLumberjack** [comment]
Thank you very much @rtissera

**Pull request merged**
