### PR TITLE
Chinese Simplified menu for emulationstation

### PR DESCRIPTION
**Pull request by shikeyu**
add zh_CN language support

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Hi, do you think you could add the news bluetooth strings ?

# Bluetooth

msgid "CONTROLLER PAIRED"
msgstr "MANETTE ASSOCIÉE"

msgid "UNABLE TO PAIR CONTROLLER"
msgstr "IMPOSSIBLE D'ASSOCIER LA MANETTE"

msgid "AN ERROR OCCURED"
msgstr "UNE ERREUR EST SURVENUE"

msgid "NO CONTROLLERS FOUND"
msgstr "AUCUNE MANETTE DÉTÉCTÉE"

msgid "PAIR A BLUETOOTH CONTROLLER"
msgstr "ASSOCIER UNE MANETTE BLUETOOTH"

**Comment by digitalLumberjack** [comment]
any news on that @shikeyu ? Could you translate the last strings ?

**Comment by tlanks** [comment]
Bluetooth

msgid "CONTROLLER PAIRED"
msgstr "MANETTE ASSOCIÉE"

msgid "UNABLE TO PAIR CONTROLLER"
msgstr "无法配对蓝牙手柄"

msgid "AN ERROR OCCURED"
msgstr "出现错误"

msgid "NO CONTROLLERS FOUND"
msgstr "未找到手柄"

msgid "PAIR A BLUETOOTH CONTROLLER"
msgstr "配对蓝牙手柄"

**Comment by shikeyu** [comment]
I'm doing it.Wait a moment.

**Pull request merged**
