### PR TITLE
Added a virtual keyboard to ES

### PR DESCRIPTION
**Pull request by rockaddicted**

### CODE REVIEW

**Comment by nadenislamarre** [comment]
omg !

**Comment by digitalLumberjack** [comment]
Ô yeah

**Comment by digitalLumberjack** [comment]
@rockaddicted did you add all the strings in poeditor.com?

**Comment by rockaddicted** [comment]
@digitalLumberjack nope I'll check poeditor.com tomorrow.

**Comment by digitalLumberjack** [comment]
O YEAH

**Pull request merged**
