### PR TITLE
emulationstation2dutch

### PR DESCRIPTION
**Pull request by Jace37**
Update the language to dutch.

### CODE REVIEW

**Comment by Jace37** [comment]
Update emulationstation2dutch.po is the good file. needed to figure out github... still don't get it right.. but i hope this can be a good use in recalbox.

**Comment by digitalLumberjack** [comment]
Hi pal, you removed the PR ?

**Comment by Jace37** [comment]
I made à new pr.  Emulationstation2dutch final.....

**Comment by Jace37** [comment]
Hi,

I removed the pr because it had major failers in the translation. So what i did is Make à new one.... Made à pr of it Also.... Srry for the problems i am pritty new to Github...... 

Greetzzz jace37 (@jakkoengelen Twitter) 

Verstuurd vanaf mijn iPhone

**Pull request closed without merging**
