### PR TITLE
Add video view to allow video preview of games in gamelist (port from RetroPie / fieldofcows work)

### PR DESCRIPTION
**Pull request by rtissera**
Please make sure your PR is ready to be merged !

- [X] You added the changes in CHANGELOG.md
- [X] You choose the right repository branch to make the PR
- [X] You described the PR as below

Changes :
- Add video preview support

Related to (put here the others PR in other repositories)
- Will need another PR to build VLC into build root and add proper dependencies

### CODE REVIEW

**Comment by substring** [comment]
Hi !

Thank you for your interest in Recalbox :)

We've been working on our own way of adding video preview that involves ffmpeg and not vlc. Looks promising and needs final tunings. So unless we can't make it with ffmpeg, we won't merge :)

**Comment by rtissera** [comment]
Ok, good to know. There's another interesting improvement from RetroPie ES fork for speeding up shutdown (saving only modified metadata, see here https://github.com/RetroPie/EmulationStation/pull/78). I have merged it in my local recalbox-emulation repo (not comitted yet). Have you got interest in merging this functionality ?

**Comment by substring** [comment]
@digitalLumberjack has been working on the start speed up
I tried the commits you mentionned but haven't noticed any real difference. As i believe i must have failed somehow (my C++ knowledge is pretty rusty), i'll just make sure no one in the team worked on that and i'll let you know. Keep in touch !

**Comment by rtissera** [comment]
OK. I'm referring to shutdown speed issue. Loading is okay on my side with thousands of ROMs on the system. Shutdown however just takes ages so I think it might be a worthy addition for people using ES with many ROMs.

**Comment by substring** [comment]
That's truly an issue, indeed ^^ I'll tell you asap :)

**Comment by substring** [comment]
@rtissera please make a new PR for the decreased shutdown time :)

**Comment by rtissera** [comment]
Closing this, will push new PR for decreased shutdown time.

**Comment by sbowler** [comment]
Any traction on the ffmpeg solution?

**Pull request closed without merging**
