### PR TITLE
SVG renderer update

### PR DESCRIPTION
**Pull request by paradadf**
All the work was taken from https://github.com/RetroPie/EmulationStation/pull/47

Fixes https://github.com/recalbox/recalbox-os/issues/1055

Haven't tested it yet!

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
@paradadf i cannot merge if you did not test. Do you need some help to test ?

**Comment by paradadf** [comment]
I tried to compile but got an error... I'll probably not be able to test it myself, so sorry
https://forum.recalbox.com/topic/3905/compile-error-creating-sd-card/13

**Comment by digitalLumberjack** [comment]
Let's try that.

**Comment by rockaddicted** [comment]
ES displays now correctly the gradients ;)

**before :**
scummvmesbefore_console

**now :**
scummvmesnow_console

**Comment by paradadf** [comment]
Nice!

**Pull request merged**
