### PR TITLE
added fast shutdown

### PR DESCRIPTION
**Pull request by digitalLumberjack**
Create a Fast Shutdown entry in shutdown menu, the process disable the gamelist saves by setting IgnoreGamelists setting to true so when SystemData are deleted they do not save the gamelist.

https://github.com/recalbox/recalbox-emulationstation/compare/rb-4.0.X...recalbox:rb-4.0.X-fastshutdown?expand=1#diff-0d7037121f70d0897714deabb3ea71e1R395

### CODE REVIEW

**Comment by tomtordev** [comment]
Thanks for this! Do you have a release planned date?

**Comment by substring** [comment]
@torra87 it's been merged to the 4.0 branch, so the feature will be available on 4.0.0beta4 :)

**Comment by tomtordev** [comment]
Great!
Do you know when beta4 will be availible?

**Comment by rockaddicted** [comment]
When it will be

**Pull request merged**
