### PR TITLE
Platform IDs

### PR DESCRIPTION
**Pull request by Supernature2k**
updating Platforms in 3 files (es_systems.cfg already updated)

### CODE REVIEW

**Comment by rockaddicted** [comment]
Nice, can you add Colecovision if not present, please ? (didnt check)

**Comment by Supernature2k** [comment]
It's there :)

`<platform>colecovision</platform>` if you want to add it in es_systems.cfg ;)

**Comment by substring** [comment]
Why not add new 4.1 system ? Dreamcast, psp, c64 ... Not sure i saw dosbox either, but apple2 is there

**Comment by Supernature2k** [comment]
Dreamcast psp and c64 are there

**Comment by digitalLumberjack** [comment]
Good job.

**Pull request merged**
