### PR TITLE
Ignore bios and devices for MAME / NeoGeo in rom directory

### PR DESCRIPTION
**Pull request by gillg**
Please make sure your PR is ready to be merged !

- [x] You added the changes in CHANGELOG.md
- [x] You choose the right repository branch to make the PR
- [ ] You described the PR as below

Changes :
- Ignore all known bios and devices for arcade/neogeo platform

### CODE REVIEW

**Comment by digitalLumberjack** [comment]
Seems nice. Thanks :)
@rockaddicted @substring what do you think ?

**Comment by substring** [comment]
Could have been done through gamelist.xml
But doing it with ES code is much smarter and can't be erased by the user
/me approves

**Comment by rockaddicted** [comment]
Very good idea, I approves too.
Thank you.

**Comment by substring** [comment]
@gillg have you only included MAME 0.78 bioses or you anticipated any newer version ?

**Comment by RomainOdeval** [comment]
@substring he used MAME 0.180 bioses and devices, if i don't make mistakes (it's a collaborator at my job. We will upgrade an arcade machine, full open source)

**Comment by gillg** [comment]
Thanks ! I have added all bios and devices from http://www.planetemu.net/roms/mame-bios-pack and http://www.planetemu.net/roms/mame-devices-pack, so it's 0.181 I think, I played with these bioses on official mame 0.181.
I'm not sure, but bios names are retrocompatibles... I guess... Else you can easely add them :p

**Comment by gillg** [comment]
Another improvement could be to init vector from a file wich list an arcade ignore-list.

**Review by substring — APPROVED** [review]

**Review by rockaddicted — APPROVED** [review]

**Review by digitalLumberjack — APPROVED** [review]
:+1:

**Pull request merged**
